#!/usr/bin/bash
#----------------------------------------------------------
# This script allows to see if there are any duplicates in 
# one of the fields of a .csv file. For example, if there 
# are any duplicates of Email addresses in that file.
# The script compares the fields in a case insensitive manner
# and also does not take into account spaces and tabs around 
# the content of the field (assuming it is a valid Email).
# If the output contains one or more lines, then duplicates
# exist and should be removed manually by searching the input
# file and deciding on which entry to remove.
# (No automatic remove!)
# The script outputs the lines which are found beyond a given 
# line down the file matching on the verified field as explained 
# above. If 2 duplicates exist, then 1 line is displayed.
# If 3 duplicates exist, then 3=(3-1)+(3-2) + 0 lines are
# displayed, related to that duplicate.
# ---------------------------------------------------------
# Written by Vitaly N. Golovach on March 16, 2016
#----------------------------------------------------------
# Set the number of the field to be checked for duplicates:
emailNF=4
#get the number of lines in the file
nl=$(gawk 'BEGIN{}{}END{print NR}' $1)
# Loop through the lines
cnt=1
while [ $cnt -le $nl ]; do
 gawk -v vnl=$cnt -v vne=$emailNF 'BEGIN{FS=","}{ \
  eml="0"; \
  if(NR==vnl){eml=$(vne); gsub(/^[ \t]+|[ \t]+$/, "", eml); rec=$0}; \
  if(eml!="0"){ \
    while(getline == 1){ \
      eml1=$(vne); \
      gsub(/^[ \t]+|[ \t]+$/, "", eml1); \
      if(tolower(eml)==tolower(eml1)){print $0} \
                       } \
              } \
  }END{}' $1
 let cnt=cnt+1
done
